version: "3.8"
services:
    db:
        container_name: be
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: password
    be:
        container_name: fe
        build: ./be
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
        volumes: 
            - ./be:/be
        environment: 
            POSTGRES_PASSWORD: password
        ports:
            - "4000:4000"
        depends_on: 
            - db
    fe:
        build: ./fe
        volumes:
            - ./fe:/fe
        ports:
            - "3000:3000"
        depends_on: 
            - be
    live-reloader-fe:
        image: apogiatzis/livereloading
        container_name: livereloader-fe
        privileged: true
        environment:
          - RELOAD_DELAY=1.5              # seconds
          - RELOAD_CONTAINER=fe
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "./fe:/fe"
    live-reloader-be:
        image: apogiatzis/livereloading
        container_name: livereloader-be
        privileged: true
        environment:
        - RELOAD_DELAY=1.5              # seconds
        - RELOAD_CONTAINER=be
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "./be:/be"