version: "3.8"
services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: password
    be:
        build: ./be
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/myapp
        environment: 
            POSTGRES_PASSWORD: password
        ports:
            - "3000:3000"
        depends_on: 
            - db
    fe:
        build: ./fe
        command: bash -c "npm install"
        volumes:
            - .:/app
        ports:
            - "3001:3000"
        depends_on: 
            - be